#!/usr/bin/python3


# Takes argument ProteinFamily
# Open ProteinFamily file
# Read in each line to a list.
	#Return list

# Open folder of Proteomes takes argument ProteinFamilyList
	#For each line in ProteinFamilylist:
		#Search through each proteome file. Line by Line 
			#If Hit: extract >header + aa sequence.
				#append to List of ORF.
		
	#return: List of ORF

#Run each enty of multifasta in ClustalO


