#!/usr/bin/python3

# Run in file generated by Find_Coregenome.py
# Looks through all files line by line, if >ref- is the startingline the node of a reference is present.

import os

DirList = []
RefPresentList = []
RefNotPresentList = [] 



DirList=os.listdir(os.getcwd())

for ProteinFamilyFile in DirList:
	Presence=False
	with open (ProteinFamilyFile,'r') as f:
		for Line in f:
			if Line.startswith('ref'):
				RefPresentList.append(f.name)
				Presence = True
	if  Presence==False:
		RefNotPresentList.append(f.name)

print 'Reference is present in : %s\nReference is NOT present in: %s'%(len(RefPresentList),len(RefNotPresentList) )
print 'Dirlen: %s' %(len(DirList))

#Creates Directory and put RefPresentList files in dir
if len(RefPresentList)>0:
	newdir='Protein_Family_Containing_Reference'
	os.system('mkdir %s'%(newdir))

	for ProteinFamily in RefPresentList:
		os.system ('mv %s %s'%(ProteinFamily,newdir))

#Creates Directory and put RefNOTPresentList files in dir
if len(RefNotPresentList)>0:
	newdir='Protein_Family_NOT_Containing_Reference_AKA_Accessory-genome'
	os.system('mkdir %s'%(newdir))

	for ProteinFamily in RefNotPresentList:
		os.system ('mv %s %s'%(ProteinFamily,newdir))
		
